name: wf6

on:
  push:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      S3_BUCKET: ${{ secrets.S3_BUCKET }}
      WEATHER_TIMEZONE: ${{ secrets.WEATHER_TIMEZONE }}
      WEATHER_COORD_DECIMALS: ${{ secrets.WEATHER_COORD_DECIMALS }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: pip

      - name: Install requirements
        run: pip install -r requirements.txt

      - name: Run main
        run: python main.py --data 50 60
